version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /app/server.py
    volumes:
      - ./demo-app:/app
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
  redis:
    image: redis:5.0.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
  cloudsql:
    image: gcr.io/cloudsql-docker/gce-proxy:1.16
    command: >
      /cloud_sql_proxy
      -instances=INSTANCE-IDENTIFIER=tcp:0.0.0.0:3306
      -dir=/cloudsql
      -credential_file=/secrets/cloudsql/credentials.json
    volumes:
      - ./key.json:/secrets/cloudsql/credentials.json
    ports:
      - "3406:3306"